### ISSUE TITLE
Can't launch app

### ISSUE THREAD

**Issue by dmnlk** [joe-re/cafe-pitch#19]
install successfully from npm but not launch.
log is here

```

Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/cafe-pitch/dist/browser/main.js:62:5)
    at __webpack_require__ (/usr/local/lib/node_modules/cafe-pitch/dist/browser/main.js:20:30)
    at /usr/local/lib/node_modules/cafe-pitch/dist/browser/main.js:40:18
    at Object.<anonymous> (/usr/local/lib/node_modules/cafe-pitch/dist/browser/main.js:43:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at loadApplicationPackage (/usr/local/lib/node_modules/cafe-pitch/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:257:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/cafe-pitch/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:289:5)

```
- OSX 10.11.5
- npm 3.9.3

**Comment by joe-re** [comment]
@dmnlk 
Thanks for reporting.  😄 
I try to reproduce it, but can't yet...
Could you tell me your node version?

**Comment by dmnlk** [comment]
versions are here

```
node -v  
v6.2.1
npm -v 
3.9.3

```

**Comment by joe-re** [comment]
@dmnlk 
I guess, you couldn't install electron-prebuilt for some reason when installed cafepitch.
Please try to move to installed cafe-pitch dir, 
~~and try `npm install electron-prebuilt` and `npm start`.~~
↑I'm sorry, can't do this. Instead, please tell me result of `node_modules/electron-prebuilt/cli.js -v`.

Or try to use binary for osx.
You can get it in below link.
https://github.com/joe-re/cafe-pitch/releases

**Comment by dmnlk** [comment]
```

[git][* master]:~/src/github.com/joe-re/cafe-pitch/ node_modules/electron-prebuilt/cli.js -v   
v0.36.12

```

I'm using binary now :)
